spring:
  application:
    name: product
  profiles:
    active: local
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config

management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/