spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  secret-key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==